###
GET http://localhost:3000/api/v1/posts?search

###

POST http://localhost:3000/api/v1/posts
Content-Type: application/json

{
    "title": "Series terbaik minggu ini",
    "body": "Inilah peringkat series-series minggu ini"
}

###
GET http://localhost:3000/api/v1/posts/9


###

PUT http://localhost:3000/api/v1/posts/9
Content-Type: application/json

{
    "title": "Orang yang pergi ke angkasa mati",
    "body": "LMAO" 
}

###
DELETE  http://localhost:3000/api/v1/posts/9


###
GET http://localhost:3000/api/v1/posts/paginate?page=1&limit=2&filter=DESC